sbh_music:
    resource: "@SbhMusicBundle/Resources/config/routing.yml"
    prefix:   /

sbh_start:
    resource: "@SbhStartBundle/Controller"
    type:     annotation
    prefix:   /

sbh_main:
    resource: "@SbhMainBundle/Controller"
    type:     annotation
    prefix:   /
